version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 585768183114.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t patel-flask-app:latest .
      - docker tag patel-flask-app:latest 585768183114.dkr.ecr.us-east-1.amazonaws.com/patel-flask-app:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 585768183114.dkr.ecr.us-east-1.amazonaws.com/patel-flask-app:latest
      - printf '[{"name":"patel-flask-container","imageUri":"%s"}]' 585768183114.dkr.ecr.us-east-1.amazonaws.com/patel-flask-app:latest > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json